---
Name: watermarkimage
---
SilverStripe\Assets\Image:
  extensions:
    - bigreja\watermarkimage\Extensions\WaterMarkExtension
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - bigreja\watermarkimage\Extensions\WaterMarkExtension
SilverStripe\SiteConfig\SiteConfig:
      extensions:
        - bigreja\watermarkimage\Extensions\watermarkimagesettings